[package]
name = "lubengine"
version = "0.1.0"
edition = "2021"

[dependencies]
colored =  { workspace = true }
lubalia_utils = { path = "../utils" }
luvam = { path = "../vm" }
lubalang = { path = "../lang" }
lubalia_compiler = { path = "../compiler" }
